//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNumericBitPrinter {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetNumericBitPrinter.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alias.
        /// </summary>
        public static string AliasLabel {
            get {
                return ResourceManager.GetString("AliasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Binary Representation.
        /// </summary>
        public static string BinaryLabel {
            get {
                return ResourceManager.GetString("BinaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data type.
        /// </summary>
        public static string DatatypeLabel {
            get {
                return ResourceManager.GetString("DatatypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Errors.
        /// </summary>
        public static string ErrorsLabel {
            get {
                return ResourceManager.GetString("ErrorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hexidecimal Representation.
        /// </summary>
        public static string HecidecimalLabel {
            get {
                return ResourceManager.GetString("HecidecimalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The dataype selected ({0}) does not support fractional values.
        /// </summary>
        public static string InvalidDecimalPointMessage {
            get {
                return ResourceManager.GetString("InvalidDecimalPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The datatype selected ({0}) does not support signed or negative values.
        /// </summary>
        public static string InvalidSignMessage {
            get {
                return ResourceManager.GetString("InvalidSignMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Datatype must be one of: sbyte, byte, short, ushort, int, uint, long, ulong, float, double, decimal.
        /// </summary>
        public static string InvalidTypeNameMessage {
            get {
                return ResourceManager.GetString("InvalidTypeNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The value {0} is invalid for datatype {1}.
        /// </summary>
        public static string InvalidValueMessage {
            get {
                return ResourceManager.GetString("InvalidValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The list is empty.
        /// </summary>
        public static string ListIsEmptyPrompt {
            get {
                return ResourceManager.GetString("ListIsEmptyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Errors.
        /// </summary>
        public static string NoErrorsLabel {
            get {
                return ResourceManager.GetString("NoErrorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter valid values for the datatype selected ({0}), separated by spaces.
        /// </summary>
        public static string NumbersPrompt {
            get {
                return ResourceManager.GetString("NumbersPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Select.
        /// </summary>
        public static string PleaseSelectLabel {
            get {
                return ResourceManager.GetString("PleaseSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the datatype for the values to parse (or Q to quit).
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have quit the application.
        /// </summary>
        public static string QuitMessage {
            get {
                return ResourceManager.GetString("QuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw Value.
        /// </summary>
        public static string RawValueLabel {
            get {
                return ResourceManager.GetString("RawValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a datatype to enable the Submit Button.
        /// </summary>
        public static string SubmitDisabledCaption {
            get {
                return ResourceManager.GetString("SubmitDisabledCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Values of type {0} selected.
        /// </summary>
        public static string TableTitle {
            get {
                return ResourceManager.GetString("TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BitPrinter: Display the bits and hex values of basic numeric datatypes in C#.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type {0} not supported.
        /// </summary>
        public static string TypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("TypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Values.
        /// </summary>
        public static string ValuesLabel {
            get {
                return ResourceManager.GetString("ValuesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Values can be separated by a space or newline..
        /// </summary>
        public static string ValuesLabelCaption {
            get {
                return ResourceManager.GetString("ValuesLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Values can be entered on separate lines, separated by a space, or both..
        /// </summary>
        public static string ValuesTextboxCaption {
            get {
                return ResourceManager.GetString("ValuesTextboxCaption", resourceCulture);
            }
        }
    }
}
